population_size: 1000
num_parents: 500
mutation_rate: 0.01
mutation_strength: 0.1
elitism: 0.1
max_gen: 100
device: "cuda"
debug: True
save_path: "./weights/snake.pth"
game:
  board_size: [16, 16]
  visualize:
    fps: 10
    window_size: [800, 800]
