population_size: 10000
num_parents: 7000
mutation_type: param
mutation_rate: 0.1
mutation_strength: 0.1
elitism: 0.1
max_gen: 1000
simulation_times: 5
device: "cuda"
debug: False
save_path: "./weights/snake.pth"
train: True
test: False
game:
  board_size: [8, 8]
  visualize:
    fps: 10
    window_size: [800, 800]
