population_size: 200
new_population: 100
selection_method: tournament
k_tournament: 10
num_parents: 100
mutation_type: layer_add
mutation_rate: 0.05
mutation_strength: 0.5
elitism: 0.05
max_gen: 1000
simulation_times: 20
device: "cpu"
workers: 4
debug: False
save_path: "./weights/snake/"
game:
  board_size: [8, 8]
  visualize:
    fps: 10
    window_size: [800, 800]
