population_size: 200
new_population: 100
selection_method: tournament
k_tournament: 10
num_parents: 100
mutation_type: param
mutation_rate: 0.05
mutation_strength: 0.2
elitism: 0.05
max_gen: 200
simulation_times: 20
device: "cpu"
workers: 8
debug: False
save_path: "./weights/dino/"
game:
  screen_size: [800, 400]
  dino_size: [50, 50]
  obstacle:
    types: ["cactus", "bird"]
    # [x, y] means randomly choose from this range
    cactus:
      y: [0, 0]
      w: [20, 40]
      h: [30, 70]
    bird:
      y: [31, 120]
      w: [20, 40]
      h: [20, 80]
  jump_power: -15
  duck_height: 30
  gravity: 1
  init_speed: -10
  change_speed_each: 1000
  accel: 1
  max_speed: -25
  win_score: 100000
  fps: 60
