population_size: 1000
num_parents: 500
mutation_type: param
mutation_rate: 0.01
mutation_strength: 0.1
elitism: 0.1
max_gen: 100
simulation_times: 10
device: "cuda"
debug: True
save_path: "./weights/dino.pth"
train: True
test: False
game:
  screen_size: [800, 400]
  dino_size: [50, 50]
  obstacle:
    types: ["cactus", "bird"]
    # [x, y] means randomly choose from this range
    cactus:
      y: [0, 0]
      w: [20, 40]
      h: [30, 70]
    bird:
      y: [31, 120]
      w: [20, 40]
      h: [20, 80]

  jump_power: -15
  duck_height: 30
  gravity: 1
  init_speed: -10
  change_speed_each: 1000
  accel: 1
  max_speed: -25
  win_score: 100000
  fps: 60
