population_size: 100
num_parents: 50
mutation_type: param
mutation_rate: 0.01
mutation_strength: 0.1
elitism: 0.1
max_gen: 50
simulation_times: 10
device: "cuda"
debug: True
save_path: "./weights/dino.pth"
train: True
test: False
game:
  screen_size: [800, 400]
  dino_size: [50, 50]
  obstacle: 
    w: 20
    h: [30, 70]
  jump_power: -15
  gravity: 1
  init_speed: -10
  change_speed_each: 1000
  accel: 1
  max_speed: -25
  win_score: 100000
  fps: 60
